stages:
  generate_data:
    cmd: python src/data/generate_dataset.py
    deps:
      - src/data/generate_dataset.py
    outs:
      - data/raw/customer_transactions.csv

  preprocess:
    cmd: python src/data/preprocessing.py
    deps:
      - src/data/preprocessing.py
      - data/raw/customer_transactions.csv
    outs:
      - data/processed/processed_transactions.csv
  
  train:
    cmd: python models/training/train.py
    deps:
      - data/processed
      - models/training/train.py
    params:
      - params.yaml
    metrics:
      - metrics.json:
          cache: false
    outs:
      - models/trained 